### ISSUE TITLE
assert flash_attn_func is not None

### ISSUE THREAD

**Issue by WenxiongLiao** [prov-gigapath/prov-gigapath#10]
```
import torch
import gigapath.slide_encoder as slide_encoder

# load from HuggingFace
model = slide_encoder.create_model(
   "./slide_encoder.pth",
   "gigapath_slide_enc12l768d",
   1536,
)
print("param #", sum(p.numel() for p in model.parameters()))

tile_embed = torch.randn(1, 5308, 1536).cuda()
coords = 28000 * torch.ones(1, 5308, 2).cuda()
model = model.cuda()

with torch.no_grad():
    with torch.cuda.amp.autocast(dtype=torch.float16):
        output = model(tile_embed, coords)
print(output)
```

**When I execute the above code, I get the following error:**

```
Traceback (most recent call last):
  File "/mnt/data/lwx/pyworkspace/multi-sur/prov-gigapath-main/load_slide_encoder.py", line 48, in <module>
    output = model(tile_embed, coords)
  File "/biolab/liaowx/anaconda3/envs/multi-sur/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt/data/lwx/pyworkspace/multi-sur/prov-gigapath-main/gigapath/slide_encoder.py", line 210, in forward
    x_list = [self.encoder(src_tokens=None, token_embeddings=x)["encoder_out"]]
  File "/biolab/liaowx/anaconda3/envs/multi-sur/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt/data/lwx/pyworkspace/multi-sur/prov-gigapath-main/gigapath/torchscale/model/../../torchscale/architecture/encoder.py", line 374, in forward
    x, l_aux_i = layer(
  File "/biolab/liaowx/anaconda3/envs/multi-sur/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt/data/lwx/pyworkspace/multi-sur/prov-gigapath-main/gigapath/torchscale/model/../../torchscale/architecture/encoder.py", line 127, in forward
    x, _ = self.self_attn(
  File "/biolab/liaowx/anaconda3/envs/multi-sur/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt/data/lwx/pyworkspace/multi-sur/prov-gigapath-main/gigapath/torchscale/model/../../torchscale/component/dilated_attention.py", line 205, in forward
    out, lse = self.attention_ops(qi, ki, vi, key_padding_mask=key_padding_mask, attn_mask=attn_mask, rel_pos=rel_pos, is_causal=is_causal)
  File "/mnt/data/lwx/pyworkspace/multi-sur/prov-gigapath-main/gigapath/torchscale/model/../../torchscale/component/multihead_attention.py", line 98, in attention_ops
    assert flash_attn_func is not None
AssertionError
```

**Comment by HanwenXuTHU** [comment]
Hi Wenxiong,

Looks like you didn't install the flash-attn successfully. Can you first check if you installed flash-attn v2? If not, please run the following command:

`pip install flash-attn --no-build-isolation`

**Comment by WenxiongLiao** [comment]
> Hi Wenxiong,
> 
> Looks like you didn't install the flash-attn successfully. Can you first check if you installed flash-attn v2? If not, please run the following command:
> 
> `pip install flash-attn --no-build-isolation`


Hi, I have solved this problem and the code works. But **a warning appeared**

`Pretrained weights not found at ./slide_encoder.pth. Randomly initialized the model!`

**I'm sure the file slide_encoder.pth exists. Why does this warning still appear?**

**Comment by HanwenXuTHU** [comment]
I don't think the script detected `./slide_encoder.pth` locally. I just test and it worked well for me. How about trying the absolute path?

**Comment by WenxiongLiao** [comment]
> I don't think the script detected `./slide_encoder.pth` in the local directory. I just test and it worked well for me. How about trying the absolute path?

Thanks, I have sloved it
