### ISSUE TITLE
slide_encoder_model can not work

### ISSUE THREAD

**Issue by xueleecs** [prov-gigapath/prov-gigapath#101]
hello i try to debug this problem more than 30 days, so i need your help ,if you convient.

1. first, the code show the error is:

slide_embeds = run_inference_with_slide_encoder(slide_encoder_model=slide_encoder_model, **tile_encoder_outputs)
     10 print(slide_embeds.keys())

File ~/.conda/envs/gigapath/lib/python3.9/site-packages/torch/utils/_contextlib.py:115, in context_decorator.<locals>.decorate_context(*args, **kwargs)
    112 @functools.wraps(func)
    113 def decorate_context(*args, **kwargs):
    114     with ctx_factory():
--> 115         return func(*args, **kwargs)

File ~/file/prov-gigapath/gigapath/torchscale/model/../../pipeline.py:187, in run_inference_with_slide_encoder(tile_embeds, coords, slide_encoder_model)
    185 # run inference
    186 with torch.cuda.amp.autocast(dtype=torch.float16):
--> 187     slide_embeds = slide_encoder_model(tile_embeds.cuda(), coords.cuda(), all_layer_embed=True)
    188 outputs = {"layer_{}_embed".format(i): slide_embeds[i].cpu() for i in range(len(slide_embeds))}
    189 outputs["last_layer_embed"] = slide_embeds[-1].cpu()

File ~/.conda/envs/gigapath/lib/python3.9/site-packages/torch/nn/modules/module.py:1501, in Module._call_impl(self, *args, **kwargs)
   1496 # If we don't have any hooks, we want to skip the rest of the logic in
   1497 # this function, and just call forward.
   1498 if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks or self._forward_pre_hooks
   1499         or _global_backward_pre_hooks or _global_backward_hooks
   1500         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1501     return forward_call(*args, **kwargs)
   1502 # Do not call functions when jit is used
   1503 full_backward_hooks, non_full_backward_hooks = [], []

File ~/file/prov-gigapath/gigapath/slide_encoder.py:209, in LongNetViT.forward(self, x, coords, all_layer_embed)
    207 # apply Transformer blocks
    208 if all_layer_embed:
--> 209     x_list = self.encoder(src_tokens=None, token_embeddings=x, return_all_hiddens=all_layer_embed)["encoder_states"]
    210 else:
    211     x_list = [self.encoder(src_tokens=None, token_embeddings=x)["encoder_out"]]

File ~/.conda/envs/gigapath/lib/python3.9/site-packages/torch/nn/modules/module.py:1501, in Module._call_impl(self, *args, **kwargs)
   1496 # If we don't have any hooks, we want to skip the rest of the logic in
   1497 # this function, and just call forward.
   1498 if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks or self._forward_pre_hooks
   1499         or _global_backward_pre_hooks or _global_backward_hooks
   1500         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1501     return forward_call(*args, **kwargs)
   1502 # Do not call functions when jit is used
   1503 full_backward_hooks, non_full_backward_hooks = [], []

File ~/file/prov-gigapath/gigapath/torchscale/model/../../torchscale/architecture/encoder.py:374, in Encoder.forward(self, src_tokens, encoder_padding_mask, attn_mask, return_all_hiddens, token_embeddings, multiway_split_position, features_only, incremental_state, positions, **kwargs)
    372 l_aux = []
    373 for idx, layer in enumerate(self.layers):
--> 374     x, l_aux_i = layer(
    375         x,
    376         encoder_padding_mask=encoder_padding_mask if incremental_state is None else None,
    377         attn_mask=attn_mask,
    378         rel_pos=rel_pos_bias,
    379         multiway_split_position=multiway_split_position,
    380         incremental_state=incremental_state[idx] if incremental_state is not None else None,
    381     )
    382     if return_all_hiddens:
    383         assert encoder_states is not None

File ~/.conda/envs/gigapath/lib/python3.9/site-packages/torch/nn/modules/module.py:1501, in Module._call_impl(self, *args, **kwargs)
   1496 # If we don't have any hooks, we want to skip the rest of the logic in
   1497 # this function, and just call forward.
   1498 if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks or self._forward_pre_hooks
   1499         or _global_backward_pre_hooks or _global_backward_hooks
   1500         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1501     return forward_call(*args, **kwargs)
   1502 # Do not call functions when jit is used
   1503 full_backward_hooks, non_full_backward_hooks = [], []

File ~/file/prov-gigapath/gigapath/torchscale/model/../../torchscale/architecture/encoder.py:127, in EncoderLayer.forward(self, x, encoder_padding_mask, attn_mask, rel_pos, multiway_split_position, incremental_state)
    125 if self.normalize_before:
    126     x = self.self_attn_layer_norm(x)
--> 127 x, _ = self.self_attn(
    128     query=x,
    129     key=x,
    130     value=x,
    131     key_padding_mask=encoder_padding_mask,
    132     attn_mask=attn_mask,
    133     rel_pos=rel_pos,
    134     incremental_state=incremental_state,
    135 )
    136 x = self.dropout_module(x)
    138 if self.drop_path is not None:

File ~/.conda/envs/gigapath/lib/python3.9/site-packages/torch/nn/modules/module.py:1501, in Module._call_impl(self, *args, **kwargs)
   1496 # If we don't have any hooks, we want to skip the rest of the logic in
   1497 # this function, and just call forward.
   1498 if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks or self._forward_pre_hooks
   1499         or _global_backward_pre_hooks or _global_backward_hooks
   1500         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1501     return forward_call(*args, **kwargs)
   1502 # Do not call functions when jit is used
   1503 full_backward_hooks, non_full_backward_hooks = [], []

File ~/file/prov-gigapath/gigapath/torchscale/model/../../torchscale/component/dilated_attention.py:205, in DilatedAttention.forward(self, query, key, value, incremental_state, key_padding_mask, attn_mask, rel_pos, is_first_step, is_causal)
    202 vi = self.gathering(v, dr, sl, is_causal=is_causal, offset=0, is_kv=True, seq_parall=self.args.seq_parallel)
    203 qi = self.gathering(q, dr, sl, is_causal=is_causal, offset=offset, is_kv=False, seq_parall=self.args.seq_parallel)
--> 205 out, lse = self.attention_ops(qi, ki, vi, key_padding_mask=key_padding_mask, attn_mask=attn_mask, rel_pos=rel_pos, is_causal=is_causal)
    207 outs.append(out)
    208 lses.append(lse)

File ~/file/prov-gigapath/gigapath/torchscale/model/../../torchscale/component/multihead_attention.py:98, in MultiheadAttention.attention_ops(self, q, k, v, key_padding_mask, attn_mask, rel_pos, is_causal)
     96     attn = rearrange(attn, '(b h) l d -> b l (h d)', h=self.num_heads)
     97 else:
---> 98     assert flash_attn_func is not None
     99     assert rel_pos is None
    100     q = rearrange(q, '(b h) l d -> b l h d', h=self.num_heads)

AssertionError: 

2. then i 

 pip install flash-attn --no-build-isolation
but it show:
Collecting flash-attn
  Using cached flash_attn-2.6.3.tar.gz (2.6 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      fatal: not a git repository (or any of the parent directories): .git
      /tmp/pip-install-7kqdp6kx/flash-attn_af83ee0db0c448b1b3d296c77a5ade8b/setup.py:95: UserWarning: flash_attn was request  ed, but nvcc was not found.  Are you sure your environment has nvcc available?  If you're installing within a container from   https://hub.docker.com/r/pytorch/pytorch, only images whose names contain 'devel' will provide nvcc.
        warnings.warn(
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-7kqdp6kx/flash-attn_af83ee0db0c448b1b3d296c77a5ade8b/setup.py", line 179, in <module>
          CUDAExtension(
        File "/data/petretto/home/gmsv2084/.conda/envs/gigapath/lib/python3.9/site-packages/torch/utils/cpp_extension.py", l  ine 1048, in CUDAExtension
          library_dirs += library_paths(cuda=True)
        File "/data/petretto/home/gmsv2084/.conda/envs/gigapath/lib/python3.9/site-packages/torch/utils/cpp_extension.py", l  ine 1179, in library_paths
          if (not os.path.exists(_join_cuda_home(lib_dir)) and
        File "/data/petretto/home/gmsv2084/.conda/envs/gigapath/lib/python3.9/site-packages/torch/utils/cpp_extension.py", l  ine 2223, in _join_cuda_home
          raise EnvironmentError('CUDA_HOME environment variable is not set. '
      OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.

      torch.__version__  = 2.0.0+cu117

      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

3. so i change my ./bashrc file in :

export CUDA_HOME=/cm/shared/apps/cuda12.2/toolkit/12.2.2
export PATH=$CUDA_HOME/bin:$PATH
export LD_LIBRARY_PATH=$CUDA_HOME/lib64:$LD_LIBRARY_PATH

4. and it can pip successful

5. but now the error is :
flash_attn_func: <function flash_attn_func at 0x15530c1de160>
Tile Embeds Shape: torch.Size([1068, 1536])
Coords Shape: torch.Size([1068, 2])
Model on CUDA: True
Tile Embeds on CUDA: True
Coords on CUDA: True
Model on CUDA: True
Tile Embeds Shape: torch.Size([1068, 1536]), on CUDA: True
Coords Shape: torch.Size([1068, 2]), on CUDA: True
An error occurred during inference: 
Traceback (most recent call last):
  File "/var/tmp/pbs.8192.hn-vm-01/ipykernel_3260738/1191723794.py", line 33, in <module>
    slide_embeds = run_inference_with_slide_encoder(slide_encoder_model=slide_encoder_model, **tile_encoder_outputs)
  File "/data/petretto/home/gmsv2084/.conda/envs/gigapath/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/data/petretto/home/gmsv2084/file/prov-gigapath/gigapath/torchscale/model/../../pipeline.py", line 187, in run_inference_with_slide_encoder
    slide_embeds = slide_encoder_model(tile_embeds.cuda(), coords.cuda(), all_layer_embed=True)
  File "/data/petretto/home/gmsv2084/.conda/envs/gigapath/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/petretto/home/gmsv2084/file/prov-gigapath/gigapath/slide_encoder.py", line 209, in forward
    x_list = self.encoder(src_tokens=None, token_embeddings=x, return_all_hiddens=all_layer_embed)["encoder_states"]
  File "/data/petretto/home/gmsv2084/.conda/envs/gigapath/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/petretto/home/gmsv2084/file/prov-gigapath/gigapath/torchscale/model/../../torchscale/architecture/encoder.py", line 374, in forward
    x, l_aux_i = layer(
  File "/data/petretto/home/gmsv2084/.conda/envs/gigapath/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/petretto/home/gmsv2084/file/prov-gigapath/gigapath/torchscale/model/../../torchscale/architecture/encoder.py", line 127, in forward
    x, _ = self.self_attn(
  File "/data/petretto/home/gmsv2084/.conda/envs/gigapath/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/petretto/home/gmsv2084/file/prov-gigapath/gigapath/torchscale/model/../../torchscale/component/dilated_attention.py", line 205, in forward
    out, lse = self.attention_ops(qi, ki, vi, key_padding_mask=key_padding_mask, attn_mask=attn_mask, rel_pos=rel_pos, is_causal=is_causal)
  File "/data/petretto/home/gmsv2084/file/prov-gigapath/gigapath/torchscale/model/../../torchscale/component/multihead_attention.py", line 98, in attention_ops
    assert flash_attn_func is not None
AssertionError

6. and my package version is :

(gigapath) [gmsv2084@ln-vm-02 ~]$ pip freeze | grep -E 'torch|flash-attn'
flash-attn==2.6.3
torch==2.0.0
torchaudio==2.0.2+cu118
torchmetrics==0.10.3
torchvision==0.15.1

so what should i do ?

**Comment by wyh196646** [comment]
same problem

**Comment by wyh196646** [comment]
@xueleecs I have sloved this problem by using 
`
pip install flash-attn --no-build-isolation -i https://pypi.tuna.tsinghua.edu.cn/simple
`

**Comment by afamiliar** [comment]
I ran into this issue as well, but the issue was with the NVIDIA driver not being found (hence `torch.cuda.is_available()` was `FALSE` and caused `flash_attn_func=None` resulting in the above error).

This resolved after fixing the driver (see: https://www.nvidia.com/en-us/drivers/ and https://docs.nvidia.com/datacenter/tesla/driver-installation-guide/index.html).

> Ubuntu 20.04
> Python 3.12
> pytorch 2.6.0+cu118
> CUDA 11.8

**Comment by salehaboualwan** [comment]
> [@xueleecs](https://github.com/xueleecs) I have sloved this problem by using `pip install flash-attn --no-build-isolation -i https://pypi.tuna.tsinghua.edu.cn/simple`

How long did it take to install flash attention? Im having severe issues with this, it's taking way too long on colab, like 1hr<. Any Ideas?
