### ISSUE TITLE
/demo/gigapath_pca_visualization_timm.ipynb

### ISSUE THREAD

**Issue by niuhulu-rui** [prov-gigapath/prov-gigapath#107]
There is a data size issue when loading the pretrained model locally in /demo/gigapath_pca_visualization_timm.ipynb.

my code:
![Uploading image.png…]()
run result:
Traceback (most recent call last):
  File "/data2/longdan/project/prov-gigapath/vis.py", line 8, in <module>
    model = timm.create_model("gigapath_slide_enc12l768d", pretrained=False, checkpoint_path=local_model_path)
  File "/data2/longdan/anaconda3/envs/prov-gigapath/lib/python3.9/site-packages/timm/models/_factory.py", line 125, in create_model
    load_checkpoint(model, checkpoint_path)
  File "/data2/longdan/anaconda3/envs/prov-gigapath/lib/python3.9/site-packages/timm/models/_helpers.py", line 101, in load_checkpoint
    incompatible_keys = model.load_state_dict(state_dict, strict=strict)
  File "/data2/longdan/anaconda3/envs/prov-gigapath/lib/python3.9/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for VisionTransformer:
	size mismatch for pos_embed: copying a param with shape torch.Size([1, 197, 1536]) from checkpoint, the shape in current model is torch.Size([1, 1370, 1536]).
	size mismatch for patch_embed.proj.weight: copying a param with shape torch.Size([1536, 3, 16, 16]) from checkpoint, the shape in current model is torch.Size([1536, 3, 14, 14]).

Process finished with exit code 1

**Comment by HanwenXuTHU** [comment]
Hi, I think it's a hugging face version issue. Did you follow the instructions we provided to specify the hf version?

**Comment by WangYijun-OUC** [comment]
> Hi, I think it's a hugging face version issue. Did you follow the instructions we provided to specify the hf version?

I have also encountered this problem. My huggingface-hub version is based on your document, namely 0.20.2, and at the same time, my timm==1.0.15. How can I solve it?
