### ISSUE TITLE
Using the  Demo code but get the dimension mismatch

### ISSUE THREAD

**Issue by BodongDu** [prov-gigapath/prov-gigapath#112]
import timm
from PIL import Image
from torchvision import transforms
import torch

tile_encoder = timm.create_model("hf_hub:prov-gigapath/prov-gigapath", pretrained=True)

transform = transforms.Compose(
    [
        transforms.Resize(256, interpolation=transforms.InterpolationMode.BICUBIC),
        transforms.CenterCrop(224),
        transforms.ToTensor(),
        transforms.Normalize(mean=(0.485, 0.456, 0.406), std=(0.229, 0.224, 0.225)),
    ]
)

img_path = "images/prov_normal_000_1.png"
sample_input = transform(Image.open(img_path).convert("RGB")).unsqueeze(0)
print(sample_input.shape)
tile_encoder.eval()
with torch.no_grad():
    output = tile_encoder(sample_input).squeeze()

Here is my running code and the error is as followed,
/home/internbddu/anaconda3/envs/gigapath/lib/python3.9/site-packages/torch/_functorch/deprecated.py:58: UserWarning: We've integrated functorch into PyTorch. As the final step of the integration, functorch.vmap is deprecated as of PyTorch 2.0 and will be deleted in a future version of PyTorch >= 2.3. Please use torch.vmap instead; see the PyTorch 2.0 release notes and/or the torch.func migration guide for more details https://pytorch.org/docs/master/func.migrating.html
  warn_deprecated('vmap', 'torch.vmap')
torch.Size([1, 3, 224, 224])
Traceback (most recent call last):
  File "/home/internbddu/prov-gigapath/test.py", line 23, in <module>
    output = tile_encoder(sample_input).squeeze()
  File "/home/internbddu/anaconda3/envs/gigapath/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/internbddu/anaconda3/envs/gigapath/lib/python3.9/site-packages/timm/models/vision_transformer.py", line 652, in forward
    x = self.forward_features(x)
  File "/home/internbddu/anaconda3/envs/gigapath/lib/python3.9/site-packages/timm/models/vision_transformer.py", line 633, in forward_features
    x = self.patch_embed(x)
  File "/home/internbddu/anaconda3/envs/gigapath/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/internbddu/anaconda3/envs/gigapath/lib/python3.9/site-packages/timm/layers/patch_embed.py", line 72, in forward
    _assert(H == self.img_size[0], f"Input height ({H}) doesn't match model ({self.img_size[0]}).")
  File "/home/internbddu/anaconda3/envs/gigapath/lib/python3.9/site-packages/torch/__init__.py", line 1209, in _assert
    assert condition, message
AssertionError: Input height (224) doesn't match model (518).
How can I fix it?

**Comment by BodongDu** [comment]
Have you been changed your mode? Why your demo code couldn't work?

**Comment by usuyama** [comment]
can you double check timm version?
