### ISSUE TITLE
Unable to load local model weights

### ISSUE THREAD

**Issue by ZHT150798** [prov-gigapath/prov-gigapath#114]
Traceback (most recent call last):
  File "/media/dell/data1/WSISR/foundation_model/prov-gigapath/load_tile_encoder.py", line 17, in <module>
    #tile_encoder, slide_encoder = load_tile_slide_encoder(local_tile_encoder_path= "/media/dell/data1/hugging_face/prov-gigapath/pytorch_model.bin", local_slide_encoder_path = "/media/dell/data1/hugging_face/prov-gigapath/slide_encoder.pth")
  File "/home/dell/anaconda3/envs/fdmodel/lib/python3.9/site-packages/timm/models/_factory.py", line 102, in create_model
    pretrained_cfg, model_name, model_args = load_model_config_from_hf(model_name)
  File "/home/dell/anaconda3/envs/fdmodel/lib/python3.9/site-packages/timm/models/_hub.py", line 138, in load_model_config_from_hf
    cached_file = download_from_hf(model_id, 'config.json')
  File "/home/dell/anaconda3/envs/fdmodel/lib/python3.9/site-packages/timm/models/_hub.py", line 133, in download_from_hf
    return hf_hub_download(hf_model_id, filename, revision=hf_revision)
  File "/home/dell/anaconda3/envs/fdmodel/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/dell/anaconda3/envs/fdmodel/lib/python3.9/site-packages/huggingface_hub/file_download.py", line 1371, in hf_hub_download
    raise LocalEntryNotFoundError(
huggingface_hub.utils._errors.LocalEntryNotFoundError: An error happened while trying to locate the file on the Hub and we cannot find the requested files in the local cache. Please check your connection and try again or make sure your Internet connection is on.

**Comment by clemsgrs** [comment]
might be good to check: https://github.com/prov-gigapath/prov-gigapath/issues/89#issuecomment-2331071948
