### ISSUE TITLE
Cancer subtyping procedure

### ISSUE THREAD

**Issue by davidhunt4** [prov-gigapath/prov-gigapath#42]
I realized that since I am not a collaborator to this repository I cannot reopen an old issue. I put a new comment on my old issue and I will copy it here: 

Hi, I have a new issue. I have followed your instructions and made a new .yaml file, new .sh file, and new .csv file adapted to my dataset. I have put h5 files with 'features' and 'coords' in a directory called NEW_h5 and I run the command
```shell
bash scripts/run_smab.sh data/NEW.h5
``` 
Everything seems to work well except it tells me that it is
```shell
Training on 3045 samples
Validating on 805 samples
Testing on 2681 samples
``` 
These are not the number of samples provided in the splits that I defined, and I do not know where these numbers come from. Do you have any insights?

**Comment by HanwenXuTHU** [comment]
Can you show me the run_smab.sh file? Maybe some configuration isn't set up properly.

**Comment by davidhunt4** [comment]
Yes, I have copied the contents of the file below. One thing I am unsure about is how "pre_split_dir" and "split_dir" work. I made them both point to the same directory that contains smab.csv, test_0.csv, train_0.csv, and val_0.csv which is the same structure as the PANDA folder. Maybe this is the issue or maybe it is something else.
```python
# Task setting
TASKCFG=finetune/task_configs/smab.yaml
DATASETCSV=dataset_csv/smab/smab.csv
PRESPLITDIR=dataset_csv/smab/ # Use the predefined split
ROOTPATH=${1-:data/NEW_h5}
MAX_WSI_SIZE=250000  # Maximum WSI size in pixels for the longer side (width or height).
TILE_SIZE=25
# Model settings
HFMODEL=hf_hub:prov-gigapath/prov-gigapath # Huggingface model name
MODELARCH=gigapath_slide_enc12l768d
TILEEMBEDSIZE=1536
LATENTDIM=768
# Training settings
EPOCH=5
GC=32
BLR=0.002
WD=0.05
LD=0.95
FEATLAYER="11"
DROPOUT=0.1
# Output settings
WORKSPACE=outputs/smab
SAVEDIR=$WORKSPACE
EXPNAME=run_epoch-${EPOCH}_blr-${BLR}_wd-${WD}_ld-${LD}_feat-${FEATLAYER}

echo "Data directory set to $ROOTPATH"

python finetune/main.py --task_cfg_path ${TASKCFG} \
               --dataset_csv $DATASETCSV \
               --root_path $ROOTPATH \
               --model_arch $MODELARCH \
               --blr $BLR \
               --layer_decay $LD \
               --optim_wd $WD \
               --dropout $DROPOUT \
               --drop_path_rate 0.0 \
               --val_r 0.1 \
               --epochs $EPOCH \
               --input_dim $TILEEMBEDSIZE \
               --latent_dim $LATENTDIM \
               --feat_layer $FEATLAYER \
               --warmup_epochs 1 \
               --gc $GC \
               --model_select last_epoch \
               --lr_scheduler cosine \
               --folds 1 \
               --dataset_csv $DATASETCSV \
               --pre_split_dir $PRESPLITDIR \
               --save_dir $SAVEDIR \
               --pretrained $HFMODEL \
               --report_to tensorboard \
               --exp_name $EXPNAME \
               --max_wsi_size $MAX_WSI_SIZE \
               --tile_size $TILE_SIZE \
               --split_dir $PRESPLITDIR
``` 
Also, my tile_size is 25 (which could be problematic in itself down the road) but I don't think that would affect the number of tiles involved in fine-tuning.

**Comment by HanwenXuTHU** [comment]
This looks good to me. The `pre_split_dir` specifies the predefined split and has a higher priority. Did you notice any "'Missing: '" outputs when running the script?

**Comment by davidhunt4** [comment]
No, I had no outputs like that. The fine-tuning task seemed to be running fine except it was using more data than I have (train_0.csv has 2067 tiles, test_0.csv has 1661, and val_0 has 519). All of the slide_id that were output, however, looked like they were my data, so it may be using duplicates somewhere.
The only error I am encountering while running is the following, at the end of Epoch 0:
```shell
Epoch: 0, Batch: 2919, Loss: 0.5976, LR: 0.0001, Time: 0.8545 sec/it, Seq len: 4247.0, Slide ID: TCGCCGACATATTCGC-1
Epoch: 0, Batch: 2939, Loss: 0.5976, LR: 0.0001, Time: 0.8550 sec/it, Seq len: 4247.0, Slide ID: ATCCTGCGTGGAATGG-1
Epoch: 0, Batch: 2959, Loss: 0.5973, LR: 0.0001, Time: 0.8553 sec/it, Seq len: 4247.0, Slide ID: AACCGCTAAGGGATGC-1
Epoch: 0, Batch: 2979, Loss: 0.5964, LR: 0.0001, Time: 0.8556 sec/it, Seq len: 4247.0, Slide ID: ATTACGCGCTGGCAGG-1
Epoch: 0, Batch: 2999, Loss: 0.5965, LR: 0.0001, Time: 0.8558 sec/it, Seq len: 4247.0, Slide ID: CAACTCCTTGATCCCG-1
Epoch: 0, Batch: 3019, Loss: 0.5956, LR: 0.0001, Time: 0.8561 sec/it, Seq len: 4247.0, Slide ID: CCCGTAGCTGGGAAGA-1
Epoch: 0, Batch: 3039, Loss: 0.5950, LR: 0.0001, Time: 0.8565 sec/it, Seq len: 4247.0, Slide ID: AATAACACTAGAACAA-1
Epoch: 0, Loss: 0.0075
TypeError: only length-1 arrays can be converted to Python scalars

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/davidhunt/prov-gigapath/finetune/main.py", line 81, in <module>
    val_records, test_records = train((train_loader, val_loader, test_loader), fold, args)
  File "/home/davidhunt/prov-gigapath/finetune/training.py", line 74, in train
    val_records = evaluate(val_loader, model, fp16_scaler, loss_fn, i, args)
  File "/home/davidhunt/prov-gigapath/finetune/training.py", line 199, in evaluate
    records['prob'][batch_idx] = Y_prob.numpy()
ValueError: setting an array element with a sequence.
```

**Comment by HanwenXuTHU** [comment]
Oh, probably because your dataset_csv/smab/smab.csv has duplicates. Can you add drop_duplicates after reading this csv? For the error you're encountering, I'll fix it soon.

**Comment by davidhunt4** [comment]
Thank you very much! That was the issue - I had multiple slide_id that were the same. I appreciate all of the help.

**Comment by HanwenXuTHU** [comment]
Great! I'll fix the last error by tomorrow.

**Comment by davidhunt4** [comment]
Hello, have you been able to go fix that error?

**Comment by HanwenXuTHU** [comment]
Hi, sorry for this late response. I just pushed the updates. Could you please pull and try it again?

**Comment by davidhunt4** [comment]
The error is gone now. Thank you!

**Comment by davidhunt4** [comment]
Hello, how do I use the fine-tuned model to generate embeddings after fine-tuning is complete?
Also, could you explain the difference between the fine-tuning method for the PCam dataset vs the PANDA dataset? I'm wondering what specifically you mean by "tile-level linear probing" and "slide-level fine tuning." What should change if I would ever want to do the PCam method on my own data?

**Comment by niuhulu-rui** [comment]
> 您好，微调完成后，如何使用微调后的模型生成嵌入？ 另外，您能解释一下 PCam 数据集和 PANDA 数据集的微调方法之间的区别吗？我想知道您所说的“平铺级线性探测”和“滑动级微调”具体是什么意思。如果我想在自己的数据上使用 PCam 方法，应该做哪些改变？

Hello, do you know how to use a fine-tuned model to generate embeddings? I would like to know about this as well.
