### ISSUE TITLE
AssertionError: Input image height (224) doesn't match model (518).

### ISSUE THREAD

**Issue by WenxiongLiao** [prov-gigapath/prov-gigapath#7]
```
import timm
from PIL import Image
from torchvision import transforms
import torch

tile_encoder = timm.create_model("hf_hub:prov-gigapath/prov-gigapath", pretrained=True)

print("param #", sum(p.numel() for p in tile_encoder.parameters()))

transform = transforms.Compose(
    [
        transforms.Resize(256, interpolation=transforms.InterpolationMode.BICUBIC),
        transforms.CenterCrop(224),
        transforms.ToTensor(),
        transforms.Normalize(mean=(0.485, 0.456, 0.406), std=(0.229, 0.224, 0.225)),
    ]
)

img_path = "./prov-gigapath-main/images/prov_normal_000_1.png"
sample_input = transform(Image.open(img_path).convert("RGB")).unsqueeze(0)

with torch.no_grad():
    output = tile_encoder(sample_input).squeeze()
    print("Model output:", output.shape)
    print(output)
```

Why do I get this error when I execute the demo:

/biolab/liaowx/anaconda3/envs/multi-sur/lib/python3.8/site-packages/torch/_functorch/deprecated.py:58: UserWarning: We've integrated functorch into PyTorch. As the final step of the integration, functorch.vmap is deprecated as of PyTorch 2.0 and will be deleted in a future version of PyTorch >= 2.3. Please use torch.vmap instead; see the PyTorch 2.0 release notes and/or the torch.func migration guide for more details https://pytorch.org/docs/master/func.migrating.html
  warn_deprecated('vmap', 'torch.vmap')
param # 1136479232
Traceback (most recent call last):
  File "/mnt/data/lwx/pyworkspace/multi-sur/prov-gigapath-main/demo/load_tile_encoder.py", line 23, in <module>
    output = tile_encoder(sample_input).squeeze()
  File "/biolab/liaowx/anaconda3/envs/multi-sur/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/biolab/liaowx/anaconda3/envs/multi-sur/lib/python3.8/site-packages/timm/models/vision_transformer.py", line 632, in forward
    x = self.forward_features(x)
  File "/biolab/liaowx/anaconda3/envs/multi-sur/lib/python3.8/site-packages/timm/models/vision_transformer.py", line 613, in forward_features
    x = self.patch_embed(x)
  File "/biolab/liaowx/anaconda3/envs/multi-sur/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/biolab/liaowx/anaconda3/envs/multi-sur/lib/python3.8/site-packages/timm/layers/patch_embed.py", line 66, in forward
    _assert(H == self.img_size[0], f"Input image height ({H}) doesn't match model ({self.img_size[0]}).")
  File "/biolab/liaowx/anaconda3/envs/multi-sur/lib/python3.8/site-packages/torch/__init__.py", line 1209, in _assert
    assert condition, message
**AssertionError: Input image height (224) doesn't match model (518).**

**Comment by WenxiongLiao** [comment]
pip install timm==1.0.3
I have solved it

**Comment by usuyama** [comment]
I’m glad to hear it worked! I’ve also added a note to the README for future reference.
