### ISSUE TITLE
Tile classification

### ISSUE THREAD

**Issue by FiReTiTi** [prov-gigapath/prov-gigapath#84]
Hi,
I installed prov-gigapath on Linux and I can run the examples you've shared.
Now I would like to use it to automatically classify tile/slide content, like: does this tile contain cancerous cel? Is this normal tissue? etc.
How can I do that?
Is there any tutorial/example?
l

**Comment by wu-bytecat** [comment]
Hello, this is my replication route. I hope it's helpful to you
I store the code on Google Cloud Drive. This is my experimental data
https://drive.google.com/file/d/1MHt_JbzRFCInIqYu47vL9a2MTdwvUMjU/view?usp=sharing
Reproduce the process
TCGA data ->processed with 1.py ->obtained H5 file ->evaluated using modified PANDA.sh
It is worth mentioning that I encountered unexpected errors during the evaluation. Please refer to the next ISSUE for details. If you encounter any solutions, please let me know. Thank you
1. py: Responsible for sending the TCGA file to the tile encoder and obtaining the H5 file
H5 file: located in the data/dinov2_features/H5 file
Data CSV file: divided into datacsv/PANDA
PANDA: Labels for all 301 TCGA images
Train: Training Set
Test: Test Set
Val: Validation set
Use the following command to reproduce the error:
Bash script/run_ unda.sh data/GigaPath_ unda_ embeddings/h5_ files

**Comment by FiReTiTi** [comment]
Hi,
Thank you for your answer.
I downloaded everything and I tried to run the code on the data, but I got this error:

    slide_encoder.pth: 100%|██████████| 345M/345M [00:10<00:00, 34.1MB/s] 
    Traceback (most recent call last):
      File "/home/thibaulg/HE/prov-gigapath/1.py", line 41, in <module>
    tile_one_slide(slide_path, save_dir=tmp_dir, level=1)
      File "/home/thibaulg/HE/prov-gigapath/gigapath/pipeline.py", line 84, in tile_one_slide
    slide_dir = process_slide(
      File "/home/thibaulg/HE/prov-gigapath/gigapath/preprocessing/data/create_tiles_dataset.py", line 294, in process_slide
    save_thumbnail(slide_image_path, thumbnail_dir / (slide_image_path.name + "_original.png"))
      File "/home/thibaulg/HE/prov-gigapath/gigapath/preprocessing/data/create_tiles_dataset.py", line 193, in save_thumbnail
    with OpenSlide(str(slide_path)) as openslide_obj:
      File "/home/thibaulg/Python/miniconda3/envs/gigapath/lib/python3.9/site-packages/openslide/__init__.py", line 179, in __init__
        self._osr = lowlevel.open(str(filename))
      File "/home/thibaulg/Python/miniconda3/envs/gigapath/lib/python3.9/site-packages/openslide/lowlevel.py", line 203, in _check_open
        raise OpenSlideUnsupportedFormatError("Unsupported or missing image file")
    openslide.lowlevel.OpenSlideUnsupportedFormatError: Unsupported or missing image file

Looking that the code, how/where do you interrogate gigapath with specific questions like tissue type, cancerous vs normal, etc.?
